In [151]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.5.1+cu124


In [152]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [153]:
scalar.ndim

0

In [154]:
scalar.item()

7

In [155]:
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [156]:
vector.ndim

1

In [157]:
vector.shape

torch.Size([2])

In [158]:
matrix=torch.tensor([[1,2]])

In [159]:
matrix.ndim

2

In [160]:
matrix.shape

torch.Size([1, 2])

In [161]:
matrix[0]

tensor([1, 2])

In [162]:
tensor=torch.tensor([[[1,2]
                      ,[2,3]]])
tensor

tensor([[[1, 2],
         [2, 3]]])

In [163]:
tensor.ndim

3

In [164]:
tensor.shape

torch.Size([1, 2, 2])

In [165]:
randomtensor=torch.rand(3,4)

In [166]:
randomimagetensor= torch.rand(224,224)
randomimagetensor.shape,randomimagetensor.ndim

(torch.Size([224, 224]), 2)

In [167]:
ones= torch.ones(224,3)


In [168]:
ones.dtype

torch.float32

In [169]:
mytensor=torch.arange(1,12,2)

In [170]:
zeros= torch.zeros_like(mytensor)
zeros

tensor([0, 0, 0, 0, 0, 0])

In [171]:
floattensor=torch.tensor([3],dtype=torch.float16,device='cpu',requires_grad=False)
floattensor.dtype

torch.float16

3 main errors you'll run into with pytorch and deep learning:
1. tensor dataype
2. tensor shape
3. tensor not on the right device

In [172]:
floattensor=floattensor.type(torch.float32)
floattensor

tensor([3.])

In [173]:
torch.mm(ones,randomtensor)

tensor([[1.4261, 1.7377, 1.7165, 1.5174],
        [1.4261, 1.7377, 1.7165, 1.5174],
        [1.4261, 1.7377, 1.7165, 1.5174],
        [1.4261, 1.7377, 1.7165, 1.5174],
        [1.4261, 1.7377, 1.7165, 1.5174],
        [1.4261, 1.7377, 1.7165, 1.5174],
        [1.4261, 1.7377, 1.7165, 1.5174],
        [1.4261, 1.7377, 1.7165, 1.5174],
        [1.4261, 1.7377, 1.7165, 1.5174],
        [1.4261, 1.7377, 1.7165, 1.5174],
        [1.4261, 1.7377, 1.7165, 1.5174],
        [1.4261, 1.7377, 1.7165, 1.5174],
        [1.4261, 1.7377, 1.7165, 1.5174],
        [1.4261, 1.7377, 1.7165, 1.5174],
        [1.4261, 1.7377, 1.7165, 1.5174],
        [1.4261, 1.7377, 1.7165, 1.5174],
        [1.4261, 1.7377, 1.7165, 1.5174],
        [1.4261, 1.7377, 1.7165, 1.5174],
        [1.4261, 1.7377, 1.7165, 1.5174],
        [1.4261, 1.7377, 1.7165, 1.5174],
        [1.4261, 1.7377, 1.7165, 1.5174],
        [1.4261, 1.7377, 1.7165, 1.5174],
        [1.4261, 1.7377, 1.7165, 1.5174],
        [1.4261, 1.7377, 1.7165, 1

In [174]:
randomtensor.T

tensor([[0.3616, 0.5780, 0.4865],
        [0.3537, 0.3881, 0.9958],
        [0.5691, 0.4058, 0.7416],
        [0.3610, 0.4490, 0.7074]])

In [175]:
randomtensor

tensor([[0.3616, 0.3537, 0.5691, 0.3610],
        [0.5780, 0.3881, 0.4058, 0.4490],
        [0.4865, 0.9958, 0.7416, 0.7074]])

In [176]:
x=torch.tensor([1,2,3,4])
x.shape

torch.Size([4])

In [177]:
x[3]

tensor(4)

In [178]:
x=x.reshape(2,2)
x

tensor([[1, 2],
        [3, 4]])

In [179]:
torch.stack([x,x.T])

tensor([[[1, 2],
         [3, 4]],

        [[1, 3],
         [2, 4]]])

In [180]:
x=x.reshape(4,1)
x

tensor([[1],
        [2],
        [3],
        [4]])

In [181]:
x.permute(1,0)

tensor([[1, 2, 3, 4]])

In [182]:
x.shape

torch.Size([4, 1])

In [183]:
array=np.array([1,2,3])
array=torch.from_numpy(array)

In [184]:
array=array.numpy()
array

array([1, 2, 3])